[2025-08-19T05:35:51.514+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T05:35:51.549+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chained_tasks_dag.generate_message manual__2025-08-19T05:35:48.423039+00:00 [queued]>
[2025-08-19T05:35:51.557+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chained_tasks_dag.generate_message manual__2025-08-19T05:35:48.423039+00:00 [queued]>
[2025-08-19T05:35:51.560+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-19T05:35:51.583+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_message> on 2025-08-19 05:35:48.423039+00:00
[2025-08-19T05:35:51.592+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T05:35:51.598+0000] {standard_task_runner.py:63} INFO - Started process 99 to run task
[2025-08-19T05:35:51.600+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chained_tasks_dag', 'generate_message', 'manual__2025-08-19T05:35:48.423039+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/chained_dag.py', '--cfg-path', '/tmp/tmpj7mgpvmk']
[2025-08-19T05:35:51.606+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask generate_message
[2025-08-19T05:35:51.683+0000] {task_command.py:426} INFO - Running <TaskInstance: chained_tasks_dag.generate_message manual__2025-08-19T05:35:48.423039+00:00 [running]> on host 6cacbbe28f9c
[2025-08-19T05:35:51.799+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chained_tasks_dag' AIRFLOW_CTX_TASK_ID='generate_message' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T05:35:48.423039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T05:35:48.423039+00:00'
[2025-08-19T05:35:51.803+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T05:35:51.804+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-19T05:35:51.805+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T05:35:51.819+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chained_tasks_dag, task_id=generate_message, run_id=manual__2025-08-19T05:35:48.423039+00:00, execution_date=20250819T053548, start_date=20250819T053551, end_date=20250819T053551
[2025-08-19T05:35:51.855+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T05:35:51.897+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T05:35:51.903+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
